# Generated by Django 6.0.5 on 2026-05-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_always_active',
            field=models.BooleanField(default=False),
        ),
    ]
